
name: generate snake animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ayamgeprek-linux
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#00ff00&color_dots=#2d2d2d&background=github-dark-dimmed
            dist/github-contribution-grid-snake-dark.svg?color_snake=#00ff00&color_dots=#2d2d2d&background=github-dark-dimmed
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
